services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_POSTGRES_DBNAME}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path", "/migrations",
        "-database",
        "postgres://${DB_POSTGRES_USER}:${DB_POSTGRES_PASSWORD}@postgres:5432/${DB_POSTGRES_DBNAME}?sslmode=${DB_POSTGRES_SSLMODE}",
        "up"
      ]

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${DB_REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
  webhook:
    build:
      context: .
      dockerfile: cmd/webhook-stub/Dockerfile
    container_name: webhook
    ports:
      - "9090:9090"
  ngrok:
    image: ngrok/ngrok:latest
    command: http webhook:9090
    depends_on:
      - webhook
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"

volumes:
  pg_data:
  redis_data: